language: objective-c
osx_image: xcode8.3
podfile: Example/Podfile

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd Example && pod repo update && pod install

script:
- xctool clean build -workspace Example/SwiftVersionUtils.xcworkspace -scheme Example/SwiftVersionUtils -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace Example/SwiftVersionUtils.xcworkspace -scheme Example/SwiftVersionUtils -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' | xcpretty