language: objective-c
osx_image: xcode8.3

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd Example && pod repo update && pod install && cd ..

after_success:
- sleep 15

script:
- xcodebuild clean build -workspace Example/SwiftVersionUtils.xcworkspace -scheme SwiftVersionUtils-Example -sdk iphonesimulator | xcpretty
- travis_retry set -o pipefail && xcodebuild test -workspace Example/SwiftVersionUtils.xcworkspace -scheme SwiftVersionUtils-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' | xcpretty