language: objective-c
osx_image: xcode8.3
podfile: Example/Podfile

script:
- xcodebuild clean build -workspace Example/SwiftVersionUtils.xcworkspace -scheme SwiftVersionUtils_Example_Tests -sdk iphonesimulator
- set -o pipefail && xcodebuild test -workspace Example/SwiftVersionUtils.xcworkspace -scheme SwiftVersionUtils_Example_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' CODE_SIGNING_REQUIRED=NO