language: objective-c
osx_image: xcode8.3

before_install:
- cd Example && pod repo update && pod install && cd ..

script:
- xcodebuild clean build -workspace Example/SwiftVersionUtils.xcworkspace -scheme SwiftVersionUtils_Example-Tests -sdk iphonesimulator
- set -o pipefail && xcodebuild test -workspace Example/SwiftVersionUtils.xcworkspace -scheme SwiftVersionUtils_Example-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3'